name: RCS CI

on:
  push:
    branches: [main]

  pull_request:

jobs:

  # =========================
  # 后端
  # =========================
  backend:
    name: BackEnd Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: RCS/BackEnd

    steps:

      # 1、下载代码
      - name: Checkout
        uses: actions/checkout@v6

      # 2、安装 .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.303'

      # 3、安装 NuGet 依赖
      - name: Restore
        run: dotnet restore SIASUN.RCS.slnx

      # 4、编译
      - name: Build
        run: dotnet build SIASUN.RCS.slnx --no-restore

      # 5、测试
      - name: Test
        run: dotnet test SIASUN.RCS.slnx --no-build


  # =========================
  # 前端
  # =========================
  frontend:
    name: FrontEnd Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: RCS/FrontEnd

    steps:

      # 1、下载代码
      - name: Checkout
        uses: actions/checkout@v6

      # 2、安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '11.9.0'

      # 3、安装 Node
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: RCS/FrontEnd/pnpm-lock.yaml


      # 4、安装前端依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5、TypeScript 检查
      - name: Type Check
        run: pnpm typecheck

      # 6、Lint
      - name: Lint
        run: pnpm oxlint

      # 7、编译
      - name: Build
        run: pnpm run build
      
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v7
        with:
          name: rcs-frontend-dist
          path: RCS/FrontEnd/dist
          retention-days: 7